# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://***
spring.datasource.username=root
spring.datasource.password=****

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.web.resources.static-locations=file:uploads/
# ===============================
# GMAIL SMTP (FOR OTP SENDING)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=***
spring.mail.username=****
spring.mail.password=****
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mailboxlayer.api.key=******
# Resend API key for transactional email service (leave empty in dev)
resend.api.key=